# NUMPY
***
[Numpy](http://www.numpy.org/) is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these objects.

## ARRAYS
***
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative values. The number of dimensions is the _rank_ of the array; the _shape_ of an array is a tuple of integers giving the size of array along each dimension.

We can initialize numpy arrays from nested Python lists and access elements using square brackets:

In [10]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(type(b))
print(b.shape)
# print(b[0,0], b[0,1], b[1,0])
print(b)

<class 'numpy.ndarray'>
(3,)
1 2 3
[1 2 3]
<class 'numpy.ndarray'>
(2, 3)
[[1 2 3]
 [4 5 6]]


numpy also provides many functions to create arrays:

In [77]:
# create an array of all zeros
c = np.zeros((2,2))
print(c, end='\n------------------------------\n')

# create an array of all ones
d = np.ones((1,2))
print(d, end='\n------------------------------\n')

# create a constant array
e = np.full((2,2),7, np.int) #providing dtype to supress future warning
print(e, end='\n------------------------------\n')

# create a 3x3 identity matrix
f = np.eye(3,3)
print(f, end='\n------------------------------\n')

# create an array filled with random values
g = np.random.random((2,2))
print(g, end='\n------------------------------\n')

[[ 0.  0.]
 [ 0.  0.]]
------------------------------
[[ 1.  1.]]
------------------------------
[[7 7]
 [7 7]]
------------------------------
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
------------------------------
[[ 0.21408557  0.86463379]
 [ 0.68451536  0.52319853]]
------------------------------


## Array Indexing
***

Numpy offers several ways to index into arrays.

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays are multidimensional, you must specify a slice for each dimension of the array:

In [88]:
# create a 2-dimensional array with shape(3,4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# use slicing to pull out sub-array consisting of first two rows
# and columns one and two
# b is an array of shape(2,2)
b = a[:2, 1:3]
print(b, end='\n------------------------------\n')

# a slice of an array is a view into the same data
# modifying it will modify the original array
print(a[0,1], end='\n------------------------------\n')
b[0,0] = 77
print(a[0,1], end='\n------------------------------\n')

[[2 3]
 [6 7]]
------------------------------
2
------------------------------
77
------------------------------
