# NUMPY
***
[Numpy](http://www.numpy.org/) is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these objects.

## ARRAYS
***
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative values. The number of dimensions is the _rank_ of the array; the _shape_ of an array is a tuple of integers giving the size of array along each dimension.

We can initialize numpy arrays from nested Python lists and access elements using square brackets:

In [1]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(type(b))
print(b.shape)
# print(b[0,0], b[0,1], b[1,0])
print(b)

<class 'numpy.ndarray'>
(3,)
1 2 3
[1 2 3]
<class 'numpy.ndarray'>
(2, 3)
[[1 2 3]
 [4 5 6]]


numpy also provides many functions to create arrays:

In [2]:
# create an array of all zeros
c = np.zeros((2,2))
print(c, end='\n------------------------------\n')

# create an array of all ones
d = np.ones((1,2))
print(d, end='\n------------------------------\n')

# create a constant array
e = np.full((2,2),7, np.int) #providing dtype to supress future warning
print(e, end='\n------------------------------\n')

# create a 3x3 identity matrix
f = np.eye(3,3)
print(f, end='\n------------------------------\n')

# create an array filled with random values
g = np.random.random((2,2))
print(g, end='\n------------------------------\n')

[[ 0.  0.]
 [ 0.  0.]]
------------------------------
[[ 1.  1.]]
------------------------------
[[7 7]
 [7 7]]
------------------------------
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
------------------------------
[[ 0.75626168  0.74035212]
 [ 0.15034637  0.50084922]]
------------------------------


## Array Indexing
***

Numpy offers several ways to index into arrays.

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays are multidimensional, you must specify a slice for each dimension of the array:

In [3]:
# create a 2-dimensional array with shape(3,4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# use slicing to pull out sub-array consisting of first two rows
# and columns one and two
# b is an array of shape(2,2)
b = a[:2, 1:3]
print(b, end='\n------------------------------\n')

# a slice of an array is a view into the same data
# modifying it will modify the original array
print(a[0,1], end='\n------------------------------\n')
b[0,0] = 77
print(a[0,1], end='\n------------------------------\n')

[[2 3]
 [6 7]]
------------------------------
2
------------------------------
77
------------------------------


We can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [4]:
# two ways of accessing the data in the middle row of the array.
# mixing integer indeixng with slices yields an array of lower rank.
# while using only slices yields an array of the same rank as the original array.

# rank 1 view of second row of array a
row_r1 = a[1, :]
# rank 2 view of second row of array a
row_r2 = a[1:2,:]

print(row_r1, row_r1.shape, '\n')
print(row_r2, row_r2.shape, '\n')

# making same distinction when accessing columns of an array
col_c1 = a[:, 1]
col_c2 = a[:, 1:2]

print(col_c1, col_c1.shape, '\n')
print(col_c2, col_c2.shape, '\n')

[5 6 7 8] (4,) 

[[5 6 7 8]] (1, 4) 

[77  6 10] (3,) 

[[77]
 [ 6]
 [10]] (3, 1) 



**Integer array indexing**: When we index into numpy arrays using slicing, the resulting array view will always be a sub-array of the original array. In contrast, integer array indexing allows us to create arbitrary arrays using data from another array.

In [5]:
a = np.array([[1,2], [3,4], [5,6]])

print(a[[0, 1, 2], [0, 1, 0]])
# the above example of integer array indexing is similar to:
print(np.array([a[0,0], a[1,1], a[2,0]]))

# when using integer array indexing we can reuse the same element from source array
print(a[[0,0], [1,1]])
# the above example is similar to:
print(np.array([a[0, 1], a[0, 1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix

In [6]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a,'\n')

# create an array of indices
b = np.array([0,2,0,1])

# select one element from each row using the indices in b
print(a[np.arange(4), b], '\n')

# mutate one element from each row using the indices in b
a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[ 1  6  7 11] 

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing**: Boolean array indexing allows us to pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that staisfy some condition.

In [7]:
# find elements of a that are bigger than 2;
# this returns a numpy array of booleans of the same shape as a, where each slot of bool_idx tells whether that 
# element of a is greater than 2
bool_idx = (a > 2)
print(bool_idx)

# we use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the true values of bool_idx
print(a[bool_idx])

# the above can be done in a single concise statement as:
print(a[a > 2])

[[ True False  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[11  3  4  5 16 17  8  9 10 21 12]
[11  3  4  5 16 17  8  9 10 21 12]


## Datatypes
***

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that can be used to construct arrays. Numpy tries to guess the datatype when we create an array, but functions used to construct arrays also include an optional argument to explictly specify the datatypes.

In [8]:
x = np.array([1,2])
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

x = np.array([1,2], dtype=np.int32)
print(x.dtype)

int64
float64
int32


## Array Math
***
Basic mathematical functions work elementwise on arrays and are available both as operator overloads and as functions in numpy module:

In [15]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

# elementwise sum
print(x + y, '\n')
print(np.add(x, y), '\n')

# elementwise difference
print(x - y, '\n')
print(np.subtract(x, y), '\n')

# elementwise product
print(x * y, '\n')
print(np.multiply(x, y), '\n')

# elementwise division
print(x / y, '\n')
print(np.divide(x, y), '\n')

# elementwise squareroot
print(np.sqrt(x, y),'\n')

[[  6.   8.]
 [ 10.  12.]] 

[[  6.   8.]
 [ 10.  12.]] 

[[-4. -4.]
 [-4. -4.]] 

[[-4. -4.]
 [-4. -4.]] 

[[  5.  12.]
 [ 21.  32.]] 

[[  5.  12.]
 [ 21.  32.]] 

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]] 

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]] 

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]] 



**dot** function is used to compute inner product of vectors, multiply a vector by a matrix and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects.

In [16]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

v = np.array([9,10])
w = np.array([11,12])

# inner product of vectors
print(v.dot(w), '\n')
print(np.dot(v, w), '\n')

# Matrix/vector product
print(x.dot(v) ,'\n')
print(np.dot(x, v), '\n')

# Matrix/matrix product
print(x.dot(y), '\n')
print(np.dot(x, y))


219 

219 

[29 67] 

[29 67] 

[[19 22]
 [43 50]] 

[[19 22]
 [43 50]]


Numpy provides many funtions for performing computations on arrays; one of the most useful us **sum**

In [17]:
# compute sum of all elements
print(np.sum(x))

# compute sum of each column
print(np.sum(x, axis=0))

# compute sum of each row
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


Data in arrays can be reshaped and manipulated in many ways. The simplest of this type of operation is transpose of a matrix (simply use the **T** attribute of the array object.

In [18]:
print(x, '\n')
print(x.T, '\n')

# taking transpose of a rank 1 matrix does nothing
v = np.array([1,2,3])
print(v, '\n')
print(v.T)

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]] 

[1 2 3] 

[1 2 3]
